<?php

use yii\db\Migration;
// use MongoDB\Client;

class m241010_103834_create_example_table extends Migration
{
    private $tableName = 'example';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $mongodb_param = require(\Yii::getAlias('@app/config/mongodb.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $dbDefault = $params['dbDefault'];
        
        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'name' => $this->string(255)->notNull(),
            'status' => $this->smallInteger()->notNull()->defaultValue(2)->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
            // 'sync_mdb' => $this->smallInteger()->defaultValue(null)->comment($dbDefault['syncMdbComment']),
            #uncomment this if u want use optimistic locking
            // 'lock_version' => $this->integer()->notNull()->defaultValue($dbDefault['lockVersion'])->comment($dbDefault['optimisticLockingComment']),
        ]);

        $dummyData = [
            [
                'name' => 'Example',
                'status' => 1,
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        #uncomment below code if you want to insert data to mongodb
        // $mongodb = new Client($mongodb_param['dsn']);
        // $collection = $mongodb->selectCollection($mongodb_param['database'], $this->tableName);
        // $collection->drop();

        foreach ($dummyData as $key => $value) {
            $this->insert('{{%' . $this->tableName . '}}', $value);

            #uncomment below code if you want to insert data to mongodb
            // $insertID['id'] = $key + 1;
            // $collection->insertOne(array_merge($insertID, $value));
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $mongodb_param = require(\Yii::getAlias('@app/config/mongodb.php'));
        $dbDefault = $params['dbDefault'];
        
        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        #uncomment below code if you want to insert data to mongodb
        // $mongodb = new Client($mongodb_param['dsn']);
        // $collection = $mongodb->selectCollection($mongodb_param['database'], $this->tableName);
        // $collection->drop();

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
